# Generated by Django 5.1.5 on 2025-01-30 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_intake', models.FloatField()),
                ('sleep_hours', models.FloatField()),
                ('meditation', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfcare.user')),
            ],
            options={
                'db_table': 'daily_activity',
            },
        ),
    ]
